export const channelStats = {
    totalViews: "74,2 TRIỆU",
    likes: "1,62M",
    shares: "52,6K",
    comments: "40,8K",
    saves: "39,2K",
    totalVideos: 439,
};

export const brandAnalysis = [
    { brand: "VinFast", videoCount: 87, avgViews: "168K" },
    { brand: "Kia", videoCount: 54, avgViews: "-" },
    { brand: "Lexus", videoCount: 18, avgViews: "107K" },
    { brand: "Audi", videoCount: 17, avgViews: "195K" },
    { brand: "Toyota", videoCount: 12, avgViews: "102K" },
    { brand: "Mazda", videoCount: 12, avgViews: "152K" },
    { brand: "BMW", videoCount: 11, avgViews: "162K" },
    { brand: "Lynk & Co", videoCount: 8, avgViews: "410K" },
    { brand: "Porsche", videoCount: 6, avgViews: "82K" },
];

export const topVideos = [
    {
        id: "01",
        title: "Tạm biệt VTV cáp...",
        views: "2,7M",
        likes: "47,6K",
        comments: "296",
        shares: "0",
        hasCrown: false,
        tags: ["STORYTELLING"],
        date: "01/08/2025",
    },
    {
        id: "02",
        title: "Tổng tài TikTok :)) – ...",
        views: "2,3M",
        likes: "58,1K",
        comments: "0",
        shares: "4.225",
        hasCrown: false,
        tags: ["LIFESTYLE"],
        date: "18/09/2025",
    },
    {
        id: "03",
        title: "Pháp sư xoá lỗi – Đẳng ...",
        views: "2,0M",
        likes: "45,8K",
        comments: "1.139",
        shares: "0",
        hasCrown: false,
        tags: ["DRAMA"],
        date: "06/11/2025",
    },
    {
        id: "04",
        title: "Đại sứ thương hiệu S...",
        views: "1,8M",
        likes: "61,0K",
        comments: "0",
        shares: "1.771",
        hasCrown: true,
        tags: ["SPONSORED"],
        date: "04/08/2025",
    },
    {
        id: "05",
        title: "Cục Đăng kiểm nên x...",
        views: "1,7M",
        likes: "25,4K",
        comments: "262",
        shares: "0",
        hasCrown: false,
        tags: ["PHẢN BIỆN"],
        date: "31/10/2025",
    },
];
